FROM nvidia/cuda:10.2-runtime

WORKDIR /home/user

RUN apt-get update && apt-get install -y python3.7 python3.7-dev python3.7-distutils python3-pip curl git

# Set default Python version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
RUN update-alternatives --set python3 /usr/bin/python3.7

WORKDIR /opt/service
COPY requirements.txt .

RUN python3 -m pip install --upgrade pip && \
    pip3 install -r requirements.txt

COPY . .

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.2/targets/x86_64-linux/lib

RUN ln -s /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so.10.2 /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so.10.1 && \
    mkdir -p /opt/logs/

# EXPOSE 5011
# ENTRYPOINT ["python3", "server.py"]
